Update requirements
Claire-LHV/vet-system pull request #2
Opened 2022-11-28 09:18 UTC by minhn9753

Minh Nguyen

2022-11-28 11:27 UTC, Claire-LHV requested changes
Request some changes

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- 1 veterinarian can be booked by many customers.
We can trace this by looking at Appointment entity. There is no need for another direct relation between the two.
We can remove this.

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- 1 service can be taken by many veterinarians
Change to 1 main responsible vet for a performed service.

[extend] how to track the surgery team, not just the responsible one. eg. Surgery entity <- need something better

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- 1 service can be taken by many veterinarians
[Minh's Idea] Specialist, General entities

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Booking confirmation can only be sent to customers after payment process is successful.
Book Appointment -> vets perform services in the appointment -> bill -> receipt
Customer can pay at the counter right after the appointment, or pay online only for user (registered customer).
Guests must pay at the counter.

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Customers need to register their pets before proceeding to book an appointment.
Not needed.
To encourage pets being registered, receptionists will help with registering their pets anytime.

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Pets need to be linked with customer accounts, so customer accounts need to be registered first in order to register for pet details.
👍

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- There is no booking time slot clash.
not non-functional, codes need to make sure of this -> need validations

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Cannot register a new account with existing email address.
duplicate

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Cannot register new pet with same details.
depends ID instead, and microchip number

2022-11-28 11:27 UTC, Claire-LHV commented on README.md
> +- Cannot make duplicate bookings: same time slot and same veterinarian.
Code should check, should not allow second booking to be confirmed. This is functional.

2022-11-30 09:45 UTC, minhn9753 commented on README.md
> +- Cannot register new pet with same details.
need to clarify again about ID, microchip number?

2022-12-01 00:07 UTC, closed without merging